[all]
master    ansible_host=93.77.180.95  ip=10.10.1.21
worker-0  ansible_host=10.10.2.14   ip=10.10.2.14
worker-1  ansible_host=10.10.3.28   ip=10.10.3.28

[bastion]
bastion ansible_host=93.77.180.95 ansible_user=ubuntu

[kube_control_plane]
master

[etcd]
master

[kube_node]
worker-0
worker-1

[k8s_cluster:children]
kube_control_plane
kube_node
